# LLM Providers Configuration
llm_providers:
  - gemma2-9b-it
  - gemma-7b-it
  - llama3-groq-70b-8192-tool-use-preview
  - llama3-groq-8b-8192-tool-use-preview
  - llama-3.1-70b-versatile
  - llama-3.1-70b-specdec
  - llama-3.1-8b-instant
  - llama-3.2-1b-preview
  - llama-3.2-3b-preview

# Project Generation Settings
project_settings:
  output_directory: results/generated_projects
  sample_size: 3  # Number of sample projects to generate

# Evaluation Metrics
evaluation_metrics:
  - accuracy
  - precision
  - recall
  - f1_score
