# LLM Providers Configuration
llm_providers:
  - groq_llama3_70b
  - groq_mixtral_8x7b
  - groq_gemma_7b
  - openai_gpt4
  - anthropic_claude

# Project Generation Settings
project_settings:
  output_directory: results/generated_projects
  sample_size: 3  # Number of sample projects to generate

# Evaluation Metrics
evaluation_metrics:
  - accuracy
  - precision
  - recall
  - f1_score